# Generated by Django 5.0.1 on 2024-02-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price_item',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
