import './globals.css'

export const metadata = {
  title: 'AlFood',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="main-container">
         {children}
      </body>
    </html>
  )
}