# Generated by Django 3.2.11 on 2024-03-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.FileField(blank=True, null=True, storage='storages.backends.s3boto3.S3Boto3Storage', upload_to='menu_item_images/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='three_d_image',
            field=models.FileField(blank=True, null=True, storage='storages.backends.s3boto3.S3Boto3Storage', upload_to='menu_item_3d_images/'),
        ),
    ]
