# Generated by Django 3.2.11 on 2024-03-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0005_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='three_d_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
