# Generated by Django 3.2.11 on 2024-03-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0006_auto_20240302_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
