# Generated by Django 3.2.11 on 2024-06-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0008_auto_20240401_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='owner',
        ),
    ]
