# Generated by Django 3.2.11 on 2024-06-25 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0009_auto_20240626_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='owner',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_licence',
            field=models.ImageField(blank=True, null=True, upload_to='vendor/licence'),
        ),
    ]
